### ISSUE TITLE
TinyMCE InputFieldType breaks repeaters if used inside ProFields Repeater Matrix

### ISSUE THREAD

**Issue by mrjcgoodwin** [ryancramerdesign/InputfieldTinyMCE#10]
It appears to be under very specific circumstances, but we think we've found a bug where TinyMCE InputFieldType breaks a standard core repeater if it is used inside ProFields Repeater Matrix.

ProcessWire 3.0.200
Matrix Repeater V8.
PHP 7.4

**To recreate:**

1. Nest a standard repeater that uses a TinyMCE text field inside a Matrix field.
2. Add to any template.
3. Edit a page using the template.

**Outcome:**

- The green title bar for the repeater item breaks and shows no info.
- You lose the ability to add a new repeater item.
- If you click to add a new matrix block item of any type on the same page, then the add new repeater option will return.
- Switching the fieldtype back to CK Editor resolves the issue.

**Comment by ryancramerdesign** [comment]
@mrjcgoodwin This is one case where you might need to use the dev branch. The PW core has some legacy TinyMCE 3.x code in InputfieldRepeater.js (leftover from years ago), which has been removed on the dev branch. There no longer needs to be any TinyMCE specific code in repeaters, but because it's there on 3.0.200 I'm thinking it's interfering, based on what you describe. Are you able to duplicate the issue with the current dev branch (3.0.207) using the latest InputfieldTinyMCE (6.0.6)? There is no TinyMCE-specific code in RepeaterMatrix, so I suspect the issue will be present in 3.0.200 whether using matrix or regular repeater, since matrix inherits most of its JS from the core. Thanks.

**Comment by mrjcgoodwin** [comment]
@ryancramerdesign Ok that makes sense. Will give this a go and report back.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

I'm also seeing this issue exactly as described. If I switch my body field back to CKEditor the problem disappears.

I've using the latest dev branch (3.0.208) and the latest TinyMCE (6.1.2). All other modules up-to-date too.

It is affecting repeaters inside a matrix block regardless of the fields the repeater has (tested with a single field (title) repeater).

I'm not too familiar with the PW admin JS - the closest explanation I can get to is that TinyMCE is preventing initRepeater() from being called when it should.

Cheers,

Chris

**Comment by mrjcgoodwin** [comment]
Hi @chriswthomson thanks for adding your feedback. Have been so busy last few months I've not had a chance to test the latest dev version our end to see if it resolves the problem. Will try and test this over the xmas break.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

This issue still persists on 3.0.209 with TinyMCE 6.1.2 and RepeaterMatrix 0.0.8.

Cheers,

Chris

**Comment by ryancramerdesign** [comment]
@mrjcgoodwin @chriswthomson Thanks, I've pushed a fix for this issue. Can you confirm it also fixes it there? Thanks.

**Comment by chriswthomson** [comment]
Thanks @ryancramerdesign, this has fixed it for me.

**Comment by mrjcgoodwin** [comment]
Thanks @ryancramerdesign - Can confirm this has resolved the issue for us too.
