### ISSUE TITLE
Properly parsing the setting overrides JSON file for templates fails.

### ISSUE THREAD

**Issue by szabeszg** [ryancramerdesign/InputfieldTinyMCE#16]
I am trying to make the [Template plugin](https://www.tiny.cloud/docs/tinymce/6/template/) work. My test _setting overrides JSON file_ is the following:

    {
      "replace_toolbar": "template",
      "templates": [
        {
          "title": "Test template",
          "description": "Adds a test paragraph.",
          "content": "<p>This is a test paragraph.</p>"
        }
      ]
    }

While `replace_toolbar` works, the `templates` setting does not. In the browser's console tinymce reports:

`tinymce.min.js:4 Invalid value passed for the templates option`

Note that all the other template options also do not seem to be parsed properly.

**Comment by szabeszg** [comment]
Follow-up: I have just realized that I edited the module's settings and not the InputField's setting.

Note that using the "Custom settings JSON text" option works and my test template shows up in the editor.

Also, when saving the path to the JSON file in the module's settings the path is valid, however, saving the very same path in the  InputField's setting reports "_Custom settings JSON file - File does not exist_".

ProcessWire 3.0.207 dev
TinyMCE rich text editor version 6.2.0.

**Comment by ryancramerdesign** [comment]
Thanks @szabeszg I've pushed fixes for both of the issues you mentioned above. The 'templates' option came down to a conflict with the $templates API variable, so that was an easy fix too. 

You may want to also add in the templates plugin to your JSON as well, so you don't have to select it manually for each field:
~~~~~
{
  "add_toolbar": "template",
  "add_plugins": "template",
  "templates": [
    {
      "title": "Test template",
      "description": "Adds a test paragraph.",
      "content": "<p>This is a test paragraph.</p>"
    }
  ]
}
~~~~~

**Comment by szabeszg** [comment]
Thanky you Ryan! Both issues are resolved on my end.

Just one more question: I guess the InputField's settings take precedence over the module's settings regarding the JSON configs. Am I correct?

> You may want to also add in the templates plugin to your JSON as well, so you don't have to select it manually for each field:

Thanks for the tip! Which makes me wonder how useful the "_Optional settings configurable per-field_" options are in the module's settings? I mean, I think it is better to keep all these settings off (except for the JSON option, of course) and use my own JSON file(s) for each InputField in the first palce. This way each InputField shares the same settings by deafult, which can be easily overwritten via JSON files applied in the InputField's setting.

**Comment by ryancramerdesign** [comment]
@szabeszg 

> Just one more question: I guess the InputField's settings take precedence over the module's settings regarding the JSON configs. Am I correct?

That's right. They merge together, with more specific type (field) overriding less specific (module), at least where they have overlapping setttings.

> Which makes me wonder how useful the "Optional settings configurable per-field" options are in the module's settings? I mean, I think it is better to keep all these settings off (except for the JSON option, of course) and use my own JSON file(s) for each InputField in the first palce. 

The goal here is just to provide enough options so that you can identify what's most useful to you. If you are going to need a particular setting on all fields, then you'll want to configure it with the module. If you are going to need a setting on some fields and not others, then you may want to define it with the field, or set it to inherit from another.
