### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/InputfieldTinyMCE#2]
Hi Ryan! I can't make TinyMCE language translation to work. I set "sl_SI" for both languages (default and Slovenian) but the editor is always in the English language. My testing shows that `$value = $this->inputfield->get("lang_$language->name");` in getLanguagePackCode() in InputfieldTinyMCE\InputfieldTinyMCESettings.php always return null. If I manually set $value to the desired language, then the editor is in the correct language. Don't know what I'm doing wrong...

**Comment by ryancramerdesign** [comment]
@matjazpotocnik The language auto-detect will work if LanguageSupport is installed in PW, and the InputfieldTinyMCE module can match up some existing language setting to a language pack name. Meaning you'd have to have the string "sl_Sl" somewhere else in ProcessWire, like in the language page name or in a previous CKEditor language setting. Since it's a 2 part language pack code "sl_Sl" I'm guessing you don't have that defined somewhere else already. 

I figured auto-detect wasn't always going to work, so this is why the module settings ask you to match languages to language packs. Go to the InputfieldTinyMCE module settings and you should see the options to select a language pack for each of your installed languages. Select the "sl_Sl" one where intended, then save and it should work. Just tested it here and it worked for me, but please let me know if I've misunderstood or if you find it still doesn't work. Thanks.

**Comment by matjazpotocnik** [comment]
Thanks for the explanation. I have LanguageSupport installed, the field type is a newly created Textarea (Multi-language), and I already selected the "sl_SI" for all languages, not just for the Slovenian language. I also created a new language with the name "sl_SI" but still no luck. Whatever I do, getLanguagePackCode() is always returning the default "en_US". There is also no "langSettings" in the javascript for InputfieldTinyMCE settings.

**Comment by matjazpotocnik** [comment]
One more thing: the language files in /site/modules/InputfieldTinyMCE/langs/ are names like sl_SI.js but the language name can't contain uppercase characters. I assume this won't work on Linux systems:

```
'language' => 'sl_si'
'language_url' => '/site/modules/InputfieldTinyMCE/langs/sl_si.js' -> it should be sl_SI.js
```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I'm not sure I fully understand yet since the language pack seems to work in testing here, but the case issue you mentioned makes sense. Do you think it could be solved if I rename the language pack files to all be lowercase?

**Comment by matjazpotocnik** [comment]
Something fishy is going on here, not sure what... When I change "Menubar dropdowns", the settings are not saved, after save it's always "default". if I change the field name from menubar to menubar1 then the setting is saved.

```
	protected function configMenubar($defaultValue) {
		/** @var InputfieldText $f */
		$f = $this->wire()->modules->get('InputfieldText');
		$f->attr('name', 'menubar1'); //changed the name from 'menubar' to 'menubar1', and on other places where it's name is used
		$f->label = $this->_('Menubar dropdowns');
```

In regard to language packs: renaming the files would work, but not sure this is the right way to go? You will have to rename them every time TinyMCE is upgraded with language files.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I misunderstood about the lowercase things. We don't want to change the case of any files here. It's not necessary that the PW language page name matches the language file name because the intention is that you match the language to the language pack in the module settings by selecting the language pack you want to use per-language. The automatic matching of language name to pack name is just a bonus helper for cases where it might be able to pre-select it, but that just covers some situations. It does the same by looking at locale and previous CKEditor settings, but again it's not always going to match and it doesn't need to because it's a configurable setting. 

From what I understand, you can't get the sl_SI language working at all in TinyMCE, even after you select it in the module settings. I can't yet duplicate that so I'd like to return to that if possible, I want to make sure you can use the intended language pack. I don't think it's a case issue because I can't find that we are doing any case conversion of the stored language pack name.

Regarding that menubar setting, that was a bug, I have just pushed a fix for that. Thanks.

**Comment by matjazpotocnik** [comment]
It looks like it was something with the session/local storage/cookies/whatever. After clearing all that, emptying the cache and after the fix with menubar I can select the language in the module settings. Thank you for the help.

**Comment by matjazpotocnik** [comment]
If I understand correctly, each checkbox in the "Optional settings configurable per-field" is "connected" to the options displayed later on. So, we have:

"Headlines" -> "Headline options"
"Context menu" -> "Context menu tools"
"??? Missing menubar ???" -> "Menubar dropdowns"
"Removed menu items" checkbox -> "Tools to remove from menubar"
"Custom styles format CSS" -> "Custom styles format CSS"
"Invalid styles" -> "Invalid styles"
"Custom JSON settings" -> "???"

It looks like the checkbox for the "Menubar dropdown" is missing? I added this in InputfieldTinyMCEConfigs.php:

```
$f->addOption('menubar',                                             
	'**' . $this->_('Menubar') . '**|' .                               
	$this->_('Specify which items to display in menu bar (when used).')
);                                                                   
```

On the other hand, if I check the "Custom JSON settings" I expected that "Default settings overrides JSON text" and "Default settings overrides JSON file" inputs should not be visible. I wrapped them into conditional:

```
if(!in_array('settingsJSON', $optionals)) {
...
}

```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik You are right, it looks like I was missing one for menubar. That's one I added last minute and must have missed the checkbox for it. (I have pushed a fix). The "settingsJSON" one actually does not need a separate input on the module config because there is already the defaultsJSON and defaultsFile settings on the module config that apply whether the settingsJSON option is selected or not. It's different from the others in that respect because defaultsJSON (or defaultsFile) can be merged with settingsJSON (or settingsFile), so both can be in use at the same time. This is for cases where someone might want to override the module-provided defaults, but also override some other custom settings at the field level too.

**Comment by matjazpotocnik** [comment]
Ok, thanks for the info. After save, I get this:

![image](https://user-images.githubusercontent.com/7663992/199075839-9247fe0a-1398-466f-be93-738bbab1acf8.png)

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Oops looks like I must have accidentally deleted after testing it, just added it back, which I think should fix that.

**Comment by matjazpotocnik** [comment]
Yes, it's fixed, so I'm closing this issue.
