### ISSUE TITLE
defaultsJSON not being used

### ISSUE THREAD

**Issue by chriswthomson** [ryancramerdesign/InputfieldTinyMCE#4]
Hi @ryancramerdesign,

Thank you for this module! I'm enjoying getting stuck in with it, and so far so good, with the one exception:

I find that "Default setting overrides JSON text" is not actually being used.

When I log where I think the value should be getting used (line 154 of InputfieldTinyMCESettings.php - getDefaults()), the value is empty even though I have valid JSON entered in the module config.

> InputfieldTinyMCE Object ( [className] => InputfieldTinyMCE [attributes] => Array ( [class] => [id] => InputfieldTinyMCE3 [name] => [value] => [type] => text [size] => 0 [maxlength] => 0 [placeholder] => [pattern] => [minlength] => 0 ) [wrapAttributes] => Array ( ) [data] => Array ( [skin] => oxide [content_css] => custom [content_css_url] => /site/templates/css/_tinymce.min.css [defaultsFile] => [defaultsJSON] => [extPluginOptions] => [styleFormatsCSS] => [optionals] => Array ( ) [headlines] => Array ( [0] => h2 [1] => h3 [2] => h4 [3] => h5 [4] => h6 ) [menubar] => default [contextmenu] => default [removed_menuitems] => default [invalid_styles] => default [label] => [description] => [icon] => [notes] => [detail] => [head] => [tabLabel] => [required] => 0 [requiredIf] => [collapsed] => 0 [showIf] => [columnWidth] => [skipLabel] => [wrapClass] => [headerClass] => [contentClass] => [addClass] => [textFormat] => 4 [renderFlags] => 0 [renderValueFlags] => 0 [prependMarkup] => [appendMarkup] => [requiredAttr] => 0 [initValue] => [stripTags] => [noTrim] => [showCount] => 0 [skin_url] => [extPluginOpts] => ) )

I'm specifically trying to use this option to remove the 'Align' options from "style_formats" - perhaps this could be handled in styleFormatsCSS like so?

> -#Align

I'm also not sure the defaultsFile path is resolving correctly - I had to enter the full server path to the existing defaults.json file for it to be found, I expected `/site/modules/InputfieldTinyMCE/defaults.json` to work.

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks, I was able to duplicate and fix the the issue where the default settings file was not working. I wasn't able to duplicate the issue with "default settings overrides JSON text". I tried replacing the style_formats JSON, removing the Align items, and that seemed to work. Keep in mind that these settings can be overridden by the field itself, since these are just defaults. Is it possible your field is already overriding the settings you want to change? If not, please paste in the JSON you are using. Regarding an `-#Align` type option for removing items, sounds useful, I'll look into it here.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

This is what I've entered on the defaultsJSON module config:

```json
{
	"style_formats": [{
			"title": "Headings",
			"items": [{
					"title": "Heading 1",
					"format": "h1"
				},
				{
					"title": "Heading 2",
					"format": "h2"
				},
				{
					"title": "Heading 3",
					"format": "h3"
				},
				{
					"title": "Heading 4",
					"format": "h4"
				},
				{
					"title": "Heading 5",
					"format": "h5"
				},
				{
					"title": "Heading 6",
					"format": "h6"
				}
			]
		},
		{
			"title": "Inline",
			"items": [{
					"title": "Bold",
					"format": "bold"
				},
				{
					"title": "Italic",
					"format": "italic"
				},
				{
					"title": "Underline",
					"format": "underline"
				},
				{
					"title": "Strikethrough",
					"format": "strikethrough"
				},
				{
					"title": "Superscript",
					"format": "superscript"
				},
				{
					"title": "Subscript",
					"format": "subscript"
				},
				{
					"title": "Code",
					"format": "code"
				}
			]
		},
		{
			"title": "Blocks",
			"items": [{
					"title": "Paragraph",
					"format": "p"
				},
				{
					"title": "Blockquote",
					"format": "blockquote"
				},
				{
					"title": "Pre",
					"format": "pre"
				}
			]
		}
	]
}
```

I did not have optionals = settingsJSON enabled in the module config. All fields should have been inheriting this from the module config. Once enabled the module level settings do not take effect either, however if I then add the above on a per-field basis then it does. I note that the input name on the field level is 'settingsJSON', not 'defaultsJSON'.

If I get a chance this afternoon I'll try and set up a fresh install to see if I can replicate with specific instructions, it could be that something in my sandbox install is getting in the way.

Cheers,

Chris

**Comment by ryancramerdesign** [comment]
@chriswthomson I tried adding your defaultsJSON to my "default settings override JSON text" and it seems to be working here:

<img width="431" alt="Screen Shot 2022-11-02 at 10 49 34 AM" src="https://user-images.githubusercontent.com/328272/199522001-85661df8-b85a-486f-bb2e-ee36ce9406f2.png">

I'm wondering if you are talking about the "Format > Align" that appears in the menubar instead? To remove that I think you'd need to add "tools to remove from menubar" a value of either `align` or one or more of `aligncenter alignjustify alignleft alignnone alignright` as needed.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

No I already have that set to `newdocument fontfamily fontsize lineheight forecolor backcolor align` which removes it from the menubar.

I'll fire up a fresh install and see if I can replicate in an environment that isn't my sandbox!

Cheers,

Chris

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks for testing. I've also added support for removing style formats like you mentioned earlier, though since using CSS opted to use the CSS standard for removing something rather than a leading hyphen:
~~~~~
#Align { display: none }
~~~~~
That removes all of the #Align items. To remove just one:
~~~~~
#Align(Center) { display: none }
~~~~~
The #Align can of course be any group name.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

That all sounds great.

I've set up a new install (3.0.206) with the default profile, installed InputfieldTinyMCE, created a 'body' field and added it to the basic-page template. The only change I've made to the default module config is to add the JSON from above. The Align menu is still appearing in the Styles dropdown.

What are we missing? The install is on PHP 8.1, maybe that's contributing to the issue? 

Cheers,

Chris

**Comment by chriswthomson** [comment]
<img width="1080" alt="Screenshot 2022-11-02 at 17 14 18" src="https://user-images.githubusercontent.com/7858587/199556616-723c3a58-b715-47a4-85a8-827a96768eeb.png">

**Comment by ryancramerdesign** [comment]
@chriswthomson I'm on PHP 8.0.8 so I suppose that's a possible difference that could account for it, but if it were the issue I think we'd be setting a notice or warning from PHP or something. So it's a mystery for the moment. Do you find that the new option to remove items works?

**Comment by matjazpotocnik** [comment]
I'm on PHP 8.1.12, and there are no warnings/errors here. If I enter the JSON provided by Chris into "default settings override JSON text", there is no align option:

![image](https://user-images.githubusercontent.com/7663992/199578225-ee11f049-101a-41c6-8fc5-2d7c940ebcba.png)

If I want to remove align from the Menubar, I must add it to "tools to remove from menubar". 

But I find it somehow confusing. There are many options, and I'm not sure where to put something to achieve the desired results. That's more problem with the MCE and the plethora of possibilities rather than this module. Do you think adding more instructions/descriptions/notes to the available options would be good? For example, in the Menubar dropdowns, I would list the available options for the top-level menu (file edit view insert format table tools help) and instructions on how to remove Menubar altogether - I entered X, and it works :-) Or what options are available to remove from toolbar.

Regarding JSON settings in the module: if both options are used, e.g. JSON text and JSON file, what would be the "final result"? And if I specify to remove newdocument (just an example) in the "Tools to remove from the menubar" but then I add it to my JSON override text/file, what option will "win"? (to anwser myself: `array_merge($this->getFromSettingsFile(), $this->getFromSettingsJSON());`

**Comment by matjazpotocnik** [comment]
![image](https://user-images.githubusercontent.com/7663992/199595600-b0b5ff1d-3e07-4b2d-8e56-f6e3dfd57759.png)
There is double text, probably enough to have it in NOTE?

**Comment by matjazpotocnik** [comment]
PHP Warning: Array to string conversion in [...\modules\InputfieldTinyMCE\InputfieldTinyMCESettings.php:369]

It's caused by this JSON in "default settings override JSON text":

```
{
"toolbar": [
    {
      "name": "history",
      "items": [ "undo", "redo"]
    }
]
}
```
and this is the inlined javascript:

```
"toolbar": [
    "Array"
],
```

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

So I've done some further debugging, and have determined that if I disable these lines in `InputfieldTinyMCESettings::getDefaults()` then it works:

```php
if(!empty(self::$caches['defaults'])) {
	if($key) return isset(self::$caches['defaults'][$key]) ? self::$caches['defaults'][$key] : null;
	return self::$caches['defaults'];
}
```

With these lines disabled, and logging `$this->inputfield` in `InputfieldTinyMCESettings::getDefaults()`, it appears that it is called 4 times before `InputfieldTinyMCE::init()` is called, and at this point `$this->inputfield->defaultsJSON` is blank. If I log it in `init()` it does have my custom defaultsJSON.

I popped in a WireException into the top of getDefaults() to get a backtrace, to see where the first of these 4 calls is coming from:

>DEBUG MODE BACKTRACE ($config->debug == true):
#0 /var/www/subdomains/blank/site/modules/InputfieldTinyMCE/InputfieldTinyMCE.module.php(400): ProcessWire\InputfieldTinyMCESettings->getDefaults()
#1 /var/www/subdomains/blank/wire/core/WireData.php(142): ProcessWire\InputfieldTinyMCE->set()
#2 /var/www/subdomains/blank/wire/core/Modules.php(3977): ProcessWire\WireData->__set()
#3 /var/www/subdomains/blank/wire/core/Modules.php(672): ProcessWire\Modules->setModuleConfigData()
#4 /var/www/subdomains/blank/wire/core/Modules.php(1457): ProcessWire\Modules->initModule()
#5 /var/www/subdomains/blank/wire/modules/Fieldtype/FieldtypeTextarea.module(286): ProcessWire\Modules->getModule()
#6 /var/www/subdomains/blank/wire/core/Field.php(975): ProcessWire\FieldtypeTextarea->getInputfield()
#7 /var/www/subdomains/blank/wire/core/Wire.php(419): ProcessWire\Field->___getInputfield()
#8 /var/www/subdomains/blank/wire/core/WireHooks.php(952): ProcessWire\Wire->_callMethod()
#9 /var/www/subdomains/blank/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks()

Still a total mystery why this isn't effecting either of you! 

PS - I'm on PHP 8.1.2 here.

Cheers,

Chris

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks, that is helpful, and I think might reveal the issue: the defaults are getting cached before all the settings are known. That becomes an issue if the defaultsJSON setting loads after the defaults have been cached. So we see different behavior just because of the order in which the settings are stored (which is basically random). I have updated the module to avoid calling the getDefaults() method until the module is initialized and caching the defaults is safe. Do you find this fixes the issue there?

@matjazpotocnik 

> But I find it somehow confusing. There are many options, and I'm not sure where to put something to achieve the desired results. 

While there are a lot of options, after awhile they start to make good sense, but it does help to locate what you need in the TinyMCE docs (https://www.tiny.cloud/docs/tinymce/6/). TinyMCE gives you a lot of control over the details and every component is configured independently. So adding or removing something from the Styles dropdown removes it from the Styles dropdown that appears in both the toolbar and menubar (if used). The menubar also has an Align tool. 

I am thinking though may be we just remove the Align from everything in our defaults.json since the only thing most would need an Align option for are images, and we already provide that with the pwimage plugin. I think most developers prefer the clients avoid doing alignment on other things. 

> ...instructions on how to remove Menubar altogether 

You can remove it just by unchecking the "menubar" option in the "Features" when editing a field. We're not used to having a RTE menubar in PW, and so I'm thinking many will opt not to use it (since it's largely redundant with the toolbar). Where I think it may have more value is if you prefer to use one over the other (menubar rather than toolbar, etc.). The menubar is probably simpler for a first-time user since it uses text labels, and everyone is used to menu bars in apps on their computer, so I think it's a good option to have. 

> Regarding JSON settings in the module: if both options are used, e.g. JSON text and JSON file, what would be the "final result"?

Both options are there so that you can choose one or the other, whichever is more convenient for your needs. They aren't meant to both be used at the same time (though I suppose you can). I prefer the convenience JSON input (no files to copy to server), but if I wanted something on the file system to maintain lots of sites at once, or for version control, then I might prefer the file instead. That's why there are both options. I think it might be confusing to use both, but if you did, the file loads first, then the JSON text/input.

> There is double text, probably enough to have it in NOTE?

Thanks, I will remove the redundant text and leave just the note.

> It's caused by this JSON in "default settings override JSON text":

Currently we require a string toolbar since it is configured with its own field in the field settings (using InputfieldTextTags input). Even if there weren't that error, your toolbar would get replaced with the one configured in field settings. To ensure there is a way to override, I have gone ahead and added support for "replace_" prefix on any settings, which will enable you to replace field-specific settings from those module JSON settings. So in your case, with the latest commits, you should be able to specify:
~~~~~
{
  "replace_toolbar": [
      {
        "name": "history",
        "items": [ "undo", "redo"]
      }
  ]
}
~~~~~

**Comment by chriswthomson** [comment]
Thanks @ryancramerdesign,

That has fixed the problem for me. I'll close this issue.

PS - on installation, the module is still listing the compatibility as 2.5, 2.6.

Thanks again,

Chris

**Comment by ryancramerdesign** [comment]
@chriswthomson 

> PS - on installation, the module is still listing the compatibility as 2.5, 2.6.

Thanks, I have corrected that. It's because I re-used the old repository for the new module rather than creating a new one, so some of the old info was still in there but hopefully that's the last of it.
