### ISSUE TITLE
Invalid value passed for the invalid_styles option

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/InputfieldTinyMCE#7]
In dev tools, I see this warning: "Invalid value passed for the invalid_styles option". It's triggered by `tinymce.init(config);` at line 615 in InputfieldTinyMCE.js. Invalid Styles textarea in the module settings is empty. config.invalid_styles is an array rather than a string? 
		

![image](https://user-images.githubusercontent.com/7663992/200142215-4680c463-3c32-489f-b1a7-034d9bdefcf8.png)

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks, I've pushed a fix. I think it's because your invalid_styles is empty and a blank PHP array translates to `[]` in JSON rather than `{}`. Since invalid_styles accept a blank string also, I've forced it to use a blank string (rather than blank array) for this case.  

For your invalid_styles, I recommend that you enter the string "default" so that it uses the default invalid_styles value, unless you really want to allow all inline styles.
